alias echon="echo "

say "Let's consider the case in which the verification is performed from scratch"
say "We first load the refinement using the command"
echon "lm CHIAExamples/SENDINGMESSAGE/Aut/Refinement.xml"
say "The refinement of the original automaton is the following"
echon "dispm"
sleep 0.3
say "And the LTL property"
echon "lpLTL [](send-><>success)"
say "The model checking activity is performed"
echon "ck"
say "Note that the the verification of the refinement takes around fourty milliseconds"
say "The size of the automata generated by the refinement checking procedure is 67 "



